--tabela das cartas

CREATE TABLE IF NOT EXISTS cartas (
    ID_CARTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    IMAGEM VARCHAR(200) NOT NULL,
    SANGUE VARCHAR(10) NOT NULL,
    RARIDADE VARCHAR(10) NOT NULL,
    LENDARIO ENUM('s', 'n') DEFAULT 'n',
    COLECAO VARCHAR(20) NOT NULL,
    ID2 INT NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL
) DEFAULT CHARSET=utf8;

--tabela usuario

CREATE TABLE IF NOT EXISTS usuario (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);